backend:
  name: git-gateway
  branch: master

media_folder: "public/images/uploads" # Où les images uploadées seront stockées
public_folder: "/images/uploads" # Chemin public pour ces images

collections:
  - name: "blog"
    label: "Articles de Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date de publication", name: "pubDate", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Contenu", name: "body", widget: "markdown" }
